import path from 'node:path';

import { Font, StyleSheet } from '@react-pdf/renderer';

import type { FontSizes } from './font-spec';

export const DEFAULT_ACCENT = '#0066CC';
const LATIN_MODERN_ROMAN = 'Latin Modern Roman';
const lmFamily = path.join(process.cwd(), 'src', 'entities', 'cv', 'pdf', 'fonts', 'lm_roman');

// React-PDF's Font.register() appends sources to a family on every call; in
// Next.js dev that means HMR reloads accumulate stale entries and the first
// registration always wins exact-weight matches. Drop the family before
// re-registering so the latest mapping takes effect.
const registeredFamilies = Font.getRegisteredFonts() as Record<string, unknown>;
delete registeredFamilies[LATIN_MODERN_ROMAN];

// Use the `-nolig` faces generated by `scripts/strip-font-ligatures.py`
// (`npm run fonts:strip-ligatures`). @react-pdf/renderer always asks fontkit to
// apply the font's default GSUB ligatures (fi, ff, fl, ffi, ...) with no way to
// disable them at runtime, and these CFF faces misrender those ligatures
// (dropped/garbled glyphs, broken copy/paste). The stripped faces remove the
// ligature lookups while keeping every glyph, so text renders correctly.
Font.register({
  family: LATIN_MODERN_ROMAN,
  fonts: [
    { src: path.join(lmFamily, 'lmroman10-regular-nolig.otf'), fontWeight: 'normal' },
    {
      src: path.join(lmFamily, 'lmroman10-italic-nolig.otf'),
      fontWeight: 'normal',
      fontStyle: 'italic',
    },
    { src: path.join(lmFamily, 'lmroman10-bold-nolig.otf'), fontWeight: 'bold' },
    {
      src: path.join(lmFamily, 'lmroman10-bolditalic-nolig.otf'),
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
  ],
});

export const pdfTheme = {
  page: {
    size: 'A4' as const,
    margin: 36,
  },
  colors: {
    text: '#1a1a1a',
    muted: '#666666',
    border: '#e5e5e5',
  },
  type: {
    family: LATIN_MODERN_ROMAN,
    sizes: {
      title: 18,
      h1: 14,
      h2: 11,
      body: 10,
      small: 9,
    },
  },
};

export type PdfDensity = 'compact' | 'normal' | 'relaxed';

const DENSITY_SCALE: Record<PdfDensity, number> = {
  compact: 0.9,
  normal: 1,
  relaxed: 1.12,
};

export type PdfStyles = ReturnType<typeof createStyles>;

export function createStyles(
  accent: string = DEFAULT_ACCENT,
  density: PdfDensity = 'normal',
  fontSizes?: FontSizes,
) {
  const scale = DENSITY_SCALE[density];
  // Resolve per-element base sizes from the optional overrides, falling back to
  // the theme defaults. Item titles and meta derive from `body` so the type
  // hierarchy (h2 = body + 1, small = body - 1) stays consistent when the user
  // only adjusts the body size. Density scaling (`fs`) is applied on top.
  const base = pdfTheme.type.sizes;
  const bodySize = fontSizes?.body ?? base.body;
  const sizes = {
    title: fontSizes?.header ?? base.title,
    h1: fontSizes?.sectionTitle ?? base.h1,
    h2: fontSizes?.body != null ? bodySize + 1 : base.h2,
    body: bodySize,
    small: fontSizes?.body != null ? Math.max(6, bodySize - 1) : base.small,
  };
  // `fs` scales font sizes; `sp` scales vertical/horizontal spacing (margins,
  // paddings, gaps). Both use the same density factor so type and whitespace
  // breathe together — 'compact' tightens both, 'relaxed' loosens both.
  const fs = (n: number) => Math.round(n * scale * 100) / 100;
  const sp = (n: number) => Math.round(n * scale * 100) / 100;
  // Line-height scales more gently than spacing so text stays legible at the
  // extremes (compact never crowds glyphs; relaxed never looks double-spaced).
  const lineScale = 1 + (scale - 1) * 0.5;
  const lh = (n: number) => Math.round(n * lineScale * 1000) / 1000;
  return StyleSheet.create({
    page: {
      paddingTop: sp(pdfTheme.page.margin),
      paddingBottom: sp(pdfTheme.page.margin),
      paddingLeft: sp(pdfTheme.page.margin),
      paddingRight: sp(pdfTheme.page.margin),
      fontFamily: pdfTheme.type.family,
      fontSize: fs(sizes.body),
      color: pdfTheme.colors.text,
      lineHeight: lh(1.15),
    },
    title: {
      fontSize: fs(sizes.title),
      fontWeight: 'bold',
      color: pdfTheme.colors.text,
      lineHeight: 1,
      marginBottom: sp(8),
      textAlign: 'center',
      letterSpacing: 0.3,
    },
    subtitle: {
      fontSize: fs(sizes.small),
      color: pdfTheme.colors.muted,
      marginBottom: sp(6),
      textAlign: 'center',
    },
    headerContactRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: sp(6),
      rowGap: sp(2),
    },
    headerContactItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerContactIcon: {
      marginRight: 3,
    },
    headerContactText: {
      fontSize: fs(sizes.small),
      color: pdfTheme.colors.text,
    },
    headerContactLink: {
      fontSize: fs(sizes.small),
      color: accent,
      textDecoration: 'none',
    },
    headerContactSeparator: {
      fontSize: fs(sizes.small),
      color: pdfTheme.colors.muted,
      marginHorizontal: 5,
    },
    headerRule: {
      marginTop: sp(4),
      marginBottom: sp(8),
      borderBottomWidth: 1,
      borderBottomColor: accent,
    },
    sectionTitle: {
      fontSize: fs(sizes.h1),
      fontWeight: 'bold',
      color: accent,
      marginTop: sp(6),
      marginBottom: sp(4),
      borderBottomWidth: 1,
      borderBottomColor: accent,
      paddingBottom: sp(7),
    },
    itemTitle: {
      fontSize: fs(sizes.h2),
      fontWeight: 'bold',
    },
    itemMeta: {
      fontSize: fs(sizes.small),
      color: pdfTheme.colors.muted,
      marginBottom: sp(1),
    },
    dateMeta: {
      fontStyle: 'italic',
    },
    paragraph: {
      marginBottom: sp(2),
    },
    bulletRow: {
      flexDirection: 'row',
      marginBottom: sp(1),
    },
    bulletDot: {
      width: 8,
      fontSize: fs(sizes.body),
      color: pdfTheme.colors.text,
    },
    bulletText: {
      flex: 1,
    },
    group: {
      marginBottom: sp(6),
    },
    itemGroup: {
      marginBottom: sp(3),
    },
    inlineMuted: {
      color: pdfTheme.colors.muted,
    },
    letterBody: {
      marginTop: sp(8),
    },
    twoColumnRow: {
      flexDirection: 'row',
      gap: sp(12),
    },
    // Column width is driven by the LayoutSpec `leftRatio` via inline flexGrow.
    // flexBasis:0 + minWidth:0 makes the columns share the row proportionally
    // and lets long text wrap instead of overflowing.
    column: {
      flexBasis: 0,
      minWidth: 0,
    },
    accentLink: {
      color: accent,
      textDecoration: 'none',
    },
  });
}

// Backwards-compat: a default-accent stylesheet used by primitives that don't
// receive a styles object. Templates pass their own per-render styles instead.
export const styles = createStyles();
